from setuptools import setup

setup(
    name="qntsim",
    version="0.1.1",
    author="Qulabs Software India Pvt Ltd",
    description="Quantum Network Simulator for quick prototyping and developement of protocols and applications",
    # packages = find_packages('src'),
    packages=['qntsim',
              'qntsim.core',
              'qntsim.core.kernel',
              'qntsim.core.resource_management',
              'qntsim.core.topology',
              'qntsim.layers',
              'qntsim.layers.application_layer',
              'qntsim.layers.link_layer',
              'qntsim.layers.network_layer',
              'qntsim.layers.physical_layer',
              'qntsim.layers.transport_layer',
              'qntsim.utils'],
    package_dir={'qntsim': 'src'},
    package_data={"qntsim":["logging.ini"]},
    install_requires=['numpy',
                      'matplotlib',
                      'json5',
                      'pandas',
                      'qutip',
                      'qiskit[all]'])
