# Generated by Django 3.2.15 on 2023-08-14 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('circuit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('circuit', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateTypes',
            fields=[
                ('gt_id', models.AutoField(primary_key=True, serialize=False)),
                ('gt_name', models.CharField(max_length=200)),
                ('single_multiple', models.CharField(max_length=10)),
                ('gt_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Layers',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=200)),
                ('layer_description', models.CharField(max_length=1000)),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.circuit')),
            ],
        ),
        migrations.CreateModel(
            name='LayerGates',
            fields=[
                ('layer_gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=200)),
                ('layer_gate_description', models.CharField(max_length=1000)),
                ('circuit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.circuit')),
                ('layer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.layers')),
            ],
        ),
        migrations.CreateModel(
            name='Gates',
            fields=[
                ('gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('gate_name', models.CharField(max_length=200)),
                ('gate_description', models.CharField(max_length=1000)),
                ('gt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gatetypes')),
            ],
        ),
    ]
