# Generated by Django 3.2.15 on 2023-08-16 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230814_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitModel',
            fields=[
                ('circuit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='gates',
            name='gt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gatetypes'),
        ),
        migrations.AlterField(
            model_name='layergates',
            name='gate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gates'),
        ),
        migrations.AlterField(
            model_name='layergates',
            name='circuit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.circuitmodel'),
        ),
        migrations.AlterField(
            model_name='layers',
            name='circuit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.circuitmodel'),
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
    ]
