# Generated by Django 3.2.15 on 2023-08-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230816_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layergates',
            name='circuit_id',
        ),
        migrations.RemoveField(
            model_name='layergates',
            name='gate_id',
        ),
        migrations.RemoveField(
            model_name='layergates',
            name='layer_id',
        ),
        migrations.RemoveField(
            model_name='layers',
            name='circuit_id',
        ),
        migrations.RemoveField(
            model_name='gates',
            name='gt_id',
        ),
        migrations.DeleteModel(
            name='CircuitModel',
        ),
        migrations.DeleteModel(
            name='GateTypes',
        ),
        migrations.DeleteModel(
            name='LayerGates',
        ),
        migrations.DeleteModel(
            name='Layers',
        ),
    ]
